Unit 10 - HW
AlinaD19/playwright_tests_with_po pull request #1
Opened 2024-06-26 18:17 UTC by AlinaD19

Unit 10 - HW

2024-06-26 18:43 UTC, hlazkov commented on src/pages/Inventory.page.js
> +    productSortingList = '[data-test=product-sort-container]';
I wouldn't store locator itself. I see you reuse it twice, but still. I would prefer to store `this.page.locator(this.productSortingList)`

2024-06-26 18:43 UTC, hlazkov commented on src/pages/Inventory.page.js
> +        await this.page.locator(this.productSortingList).click();
Same here. In case we store `this.page.locator(this.productSortingList)`, no sence in having click method saved here.

2024-06-26 18:45 UTC, hlazkov commented on src/pages/Inventory.page.js
> +            price.flatMap((itemPrice) => itemPrice.match(/\d+(\.\d+)?/g));
I went googling flatMap method :) Why usual map is not enough here?

2024-06-26 18:46 UTC, hlazkov commented on src/tests/test1.spec.js
> +        // Verify sorting A to Z
Lets have separate tests for different sorting!

2024-06-26 18:46 UTC, hlazkov requested changes
Please recheck on comments provided

2024-06-27 09:54 UTC, AlinaZhykharieva approved these changes

2024-06-27 09:55 UTC, AlinaZhykharieva commented
Привіт, я апрувнула. тепер можна спробувати зробити параметризовані тести. Спочатку можна згрупувати 1 і 2 та 3 і 4. А потім якщо вийде то і всі разом

2024-06-27 09:56 UTC, merged